name: Dev Deployment

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    environment: DEV
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2

      #  Package jar

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true


      # Heroku login
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP }}
          V_HOST: ${{ secrets.DB_HOST }}
          V_PORT: ${{ secrets.DB_PORT }}
          V_NAME: ${{ secrets.DB_NAME }}
          V_USER: ${{ secrets.DB_USER }}
          V_PASSWORD: ${{ secrets.DB_PASSWORD }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            usedocker: true
            docker_build_args: |
              V_HOST
              V_PORT
              V_NAME
              V_USER
              V_PASSWORD